name: Release Software Artifact (Butterfly or Leonardo) to Portale Licenze

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: whether the final installed artifact should point to staging or production apis, and whether the final artifact should be uploaded to staging or production backoffice'
        required: true
      flavor:
        description: 'Flavor: which flavor of the artifact should be created by the setup'
        required: true
      version:
        description: 'Version: the sem-ver of the artifact. Will also be appended to the setup filename'
        required: true
        type: string

jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Build
        run: dotnet build
      - name: Run - read args from command line and print them
        run: dotnet run --project .\ConsoleApp\ConsoleApp.csproj --flavor="${{inputs.flavor}}" --environment="${{inputs.environment}}" --version="${{inputs.version}}"